version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.9.0

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
          - dependency-cache-
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  retweet:
    <<: *defaults
    steps:
      - install
      - run: node index.js

workflows:
  version: 2

  test:
    jobs:
      - sendfeed

  poll:
    triggers:
      - schedule:
          # Every day at 8 (CEST) (6 UTC)
          cron: "35 17 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - sendfeed
