# version: 2.1

# defaults: &defaults
#   working_directory: ~/repo
#   docker:
#     - image: circleci/node:12.9.0

# commands:
#   install:
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#           - dependency-cache-{{ checksum "package.json" }}
#           - dependency-cache-
#       - run: npm install
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - node_modules

# jobs:
#   sendfeed:
#     <<: *defaults
#     steps:
#       - install
#       - run: node index.js

# workflows:
#   version: 2

#   test:
#     jobs:
#       - sendfeed

#   everymorning:
#     triggers:
#       - schedule:
#           # Every day at 8 (CEST) (6 UTC)
#           cron: "0 6 * * *"
#           filters:
#             branches:
#               only:
#                 - master
#     jobs:
#       - sendfeed
